<a href="https://colab.research.google.com/github/Yewwys/Google-Colab/blob/main/00_pytorch_lecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

## Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [12]:
vector = torch.tensor([[7,7,3],[6,6,6]])
vector

tensor([[7, 7, 3],
        [6, 6, 6]])

In [13]:
vector.ndim

2

In [14]:
vector.shape

torch.Size([2, 3])

In [15]:
# Tensor
tensor = torch.tensor([[[1,2,3],
                        [323,33,78],
                        [34,78,44]]])
tensor

tensor([[[  1,   2,   3],
         [323,  33,  78],
         [ 34,  78,  44]]])

In [16]:
tensor.shape

torch.Size([1, 3, 3])

In [19]:
tensor[0,2,0]

tensor(34)

In [24]:
four = torch.tensor([[[[10,20,11],
                       [67,88,56]],
                      [[5,67,89],
                       [45,90,11]],
                      ],
                     [[[100,200,300],
                       [454,444,333]],
                      [[11,22,33],
                       [90,45,34]]]])
four

tensor([[[[ 10,  20,  11],
          [ 67,  88,  56]],

         [[  5,  67,  89],
          [ 45,  90,  11]]],


        [[[100, 200, 300],
          [454, 444, 333]],

         [[ 11,  22,  33],
          [ 90,  45,  34]]]])

In [26]:
four.ndim
four.shape

torch.Size([2, 2, 2, 3])

In [35]:
# wanna get 22
four[1,1,0,1]

tensor(22)

In [40]:
#  454    วิธีindexคือค่อยๆเช็กแต่ละdim
four[1,0,1,0]

tensor(454)